apiVersion: v1
kind: Service
metadata:
  name: sprintboard-api
  namespace: cicd
  labels:
    app: sprintboard-api
spec:
  selector:
    app: sprintboard-api
  ports:
    - name: http
      port: 9400
      targetPort: 9400
      nodePort: 30940
  type: NodePort

